### ISSUE TITLE
Table's width cuts off karma numbers

### ISSUE THREAD

**Issue by Ganon11** [arubinoff/slack-karmabot#12]
See https://files.slack.com/files-pri/T0JBFSZ61-F6Q2UGU2H/pasted_image_at_2017_08_17_09_36_am.png

Setting the `max-width` of `karmalist` to a larger value gives it enough room to render the number apart from the vertical scroll bar.

**Comment by arubinoff** [comment]
this is fixed but i never closed this issue because the karma site isn't on git. still, closing this.
